# Generated by Django 3.0.7 on 2020-06-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeTwitter', '0007_auto_20200621_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='_profile_following_+', to='NeTwitter.Profile', verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='NeTwittet/media/profile_photo', verbose_name='Фото профиля'),
        ),
    ]
